### ISSUE TITLE
Provide means to convert to RGBA

### ISSUE THREAD

**Issue by roaral** [bzotto/rgba_bitmap#4]
One problem is that there aren't any easy ways to produce RGBA images. Someone may have generated a logo in Gimp and now they need to load it as an OpenGL texture to use it in ImGui... this would be such an an easy matter if the image was in RGBA format. However, Gimp cannot save RGBA images. Gimp cannot save _any_ image format that is easy to read in order to convert it to RGBA, or to an OpenGL texture. We need _something_.

For myself I made a small program, png2rgba.cpp. It seems to work pretty well with most forms of PNG (I tried it on the PngSuite set). Take it, convert it to pure C or do whatever. I think RGBA would gain more traction if there was some way to _produce_ RGBA:
https://gist.github.com/roaral/c6cc2eae2b65c1fdb27dcdb86725cfab

**Comment by roaral** [comment]
$ g++ png2rgba.cpp -Wall -O3 -lpng -o png2rgba

**Comment by bzotto** [comment]
Love that you did this! I'd be more than happy to just include it in the repo here if you'd like. I'm a bit of a GitHub dummy so open to suggestions on how to best do that.

**Comment by roaral** [comment]
(Sorry for taking so long to respond, I totally forgot about it)
To include it in the repo, you can for instance follow these steps:

- Open https://github.com/bzotto/rgba_bitmap
- Press "Add file / Create a new file"
- Create a new subdirectory by adding a file with a trailing slash, for instance named "converters/" (I haven't tried this)
- Change to the new folder "converters"
- Press "Add file / Create a new file" again, name the new file "png2rgba.cpp"
- Paste in the source code

I have added a header to the gist, attributing the original code as best as I can. The original was said to be published under the X11 license, but without including the actual X11 license. However the X11 license basically says "The [...] copyright notice [...] shall be included in all copies [...]", so I did that.

**Comment by bzotto** [comment]
Fantastic. Done and done. Thanks so much for putting it together as well as the easy instructions (I would never in one million years have figured out the "create directory by typing trailing slash" trick).
